// <auto-generated />
using AntiGreenCodes.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntiGreenCodes.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220610141155_SeedMoreProducts")]
    partial class SeedMoreProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AntiGreenCodes.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rare",
                            Url = "rare"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pokemon Go",
                            Url = "pokemon-go"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sword & Shield",
                            Url = "sword-and-shield"
                        });
                });

            modelBuilder.Entity("AntiGreenCodes.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Pokemon Promo Single Charizard Oversized Card #4/102. Card measures approximately 8x6",
                            ImageUrl = "https://imgs.search.brave.com/tm0MvvNfuLuBiczH_exNEcVJy3gUpfXugRk1NMoGAbE/rs:fit:500:687:1/g:ce/aHR0cHM6Ly93d3cu/c2VsbDJiYm5vdmVs/dGllcy5jb20vbW01/L3Bva2Vtb24vUEtf/QjJfaDQuanBn",
                            Price = 300.00m,
                            Title = "Charizard"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Pokemon Sword & Shield Base Set Rare Holo Cinderace",
                            ImageUrl = "https://imgs.search.brave.com/zu3PB4vXaoR4oOiIa6w_uTcSy9e8x3Ek-hpjTLSBNFQ/rs:fit:1200:1200:1/g:ce/aHR0cHM6Ly9jZG4x/MS5iaWdjb21tZXJj/ZS5jb20vcy0wa3Z2/OS9pbWFnZXMvc3Rl/bmNpbC8xOTIwdy9w/cm9kdWN0cy8zMjEy/MjMvNDY0MTU4L3Bv/a2Vtb25zd29yZDI2/c2hpZWxkMDM1X182/MjU2OC4xNTgwNzY3/MzI5LmpwZz9jPTI",
                            Price = 500.00m,
                            Title = "Cinderace"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Pokemon Promo Single Mew Card",
                            ImageUrl = "https://imgs.search.brave.com/BUKX4p_Xu2peOCKs4Ehj_CeFHptCai02zhPu-Tj3TWM/rs:fit:1000:1200:1/g:ce/aHR0cHM6Ly9pNS53/YWxtYXJ0aW1hZ2Vz/LmNvbS9hc3IvY2M0/ZDQ3Y2QtMWIwMi00/Yzg4LWJhNWEtMjVj/MjBkMWVkNzdiXzEu/YzZlOGFkZTA4ODgw/YmMyOTVhY2E1Y2Q2/ZDc1N2Q0NzUuanBl/Zw",
                            Price = 700.00m,
                            Title = "Mew"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Roxanne : SWORD AND SHIELD ASTRAL RADIANCE 188/189 - Pokemon Single Card. Mint / near mint condition trading card.",
                            ImageUrl = "https://cdn.chaoscards.co.uk/uploads/prod_img/2_195828_e.png?v=1653661944",
                            Price = 30.00m,
                            Title = "Roxane"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Galarian Articuno V : SWORD AND SHIELD - CHILLING REIGN - 169/198 - Pokemon Single Card",
                            ImageUrl = "https://cdn.chaoscards.co.uk/uploads/prod_img/2_177622_e.png?v=1623939679",
                            Price = 300.00m,
                            Title = "Articuno"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Ultra Ball : SWORD AND SHIELD - BRILLIANT STARS 186/172 - Pokemon Single Card",
                            ImageUrl = "https://cdn.chaoscards.co.uk/uploads/prod_img/2_189981_e.png?v=1645795290",
                            Price = 20.00m,
                            Title = "UltraBall"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Pokemon Trading Card Game Team Up Uncommon Pupitar #80",
                            ImageUrl = "https://imgs.search.brave.com/yOjMw_LpAcMeJutM-1CPipiXe322XgPR6-I7OUTY-Eo/rs:fit:1200:1200:1/g:ce/aHR0cHM6Ly9jZG4x/MS5iaWdjb21tZXJj/ZS5jb20vcy0wa3Z2/OS9pbWFnZXMvc3Rl/bmNpbC8yNTYwdy9w/cm9kdWN0cy8yODYx/NzYvNDAyMDc2L3Bv/a2Vtb250ZWFtdXAw/ODBfXzE1NTEwLjE1/NDkwNTEwNjMuanBn/P2M9Mg",
                            Price = 30.00m,
                            Title = "Pupitar"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Pokemon Shining Fates Rare Celebi #3",
                            ImageUrl = "https://tools.toywiz.com/_images/_webp/_products/lg/pokemonshiningfates003.webp",
                            Price = 70.00m,
                            Title = "Celebi"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Pokemon Gym Challenge Rare Holo Misty's Gyarados #13",
                            ImageUrl = "https://tools.toywiz.com/_images/_webp/_products/lg/pokemongc013.webp",
                            Price = 150.00m,
                            Title = "Gyarados"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Pokemon Sword & Shield Evolving Skies Ultra Rare Rayquaza V #194",
                            ImageUrl = "https://tools.toywiz.com/_images/_webp/_products/lg/pokemonevolvingskies194.webp",
                            Price = 100.00m,
                            Title = "Rayquaza"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Pokemon Astral Radiance Secret Rare Origin Form Palkia-VSTAR #208",
                            ImageUrl = "https://tools.toywiz.com/_images/_webp/_products/lg/pokemonastralradiance208.webp",
                            Price = 100.00m,
                            Title = "Palkia"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Pokemon Astral Radiance Ultra Rare Origin Forme Dialga-V #177",
                            ImageUrl = "https://tools.toywiz.com/_images/_webp/_products/lg/pokemonastralradiance177.webp",
                            Price = 700.00m,
                            Title = "Dialga"
                        });
                });

            modelBuilder.Entity("AntiGreenCodes.Shared.Product", b =>
                {
                    b.HasOne("AntiGreenCodes.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
